### ISSUE TITLE
Breaks some NoNpDRM games

### ISSUE THREAD

**Issue by octopuserectus** [xyzz/pngshot#1]
I found out that this plugin causes either crashes with error C2-12828-1 when trying to run games  (Oreshika, Odin Sphere, Wipeout, Muramasa, Child of Light and others) or hangs the games while they are displaying loading indicator (Hohokum). I have not paid attention if it happens with both EU- and US-versions of the same game, but as far as I remember, while I was trying to find out what is causing the issue, I have tried both regions for the same game and the error was present both times. I have excluded incompatibility with other plugins I might have installed by disabling them, of course except for the NoNpDRM one. Not sure why it is happening.

**Comment by xyzz** [comment]
Confirmed by another user that at least some of these work fine. Check that you installed plugin correctly.
