### ISSUE TITLE
[Request or Help] Patching filename for each shot?

### ISSUE THREAD

**Issue by alpakeno** [xyzz/pngshot#11]
I want to store files in ux0:screenshot folder for each capture ( as i use vitashell instead of vita photo app )
using taiInjectData to change the const char *path is not working for each capture.
So I can't seem to be able to do it...
Any help would be great.
Thanks.

```
SceDateTime time;
sceRtcGetCurrentClockLocalTime(&time);
char fname[256];
sprintf(fname, "ux0:/screenshot/%d-%d-%d-%d%d%d.png", time.year, time.month, time.day, time.hour, time.minute, time.second);
```

**Comment by xyzz** [comment]
It's going to be a different method from this plugin's, as the original SceShell uses some API for photo import, and that's the part which is responsible for renaming the file, the filename you see in the code is just a temporary thing.

**Comment by alpakeno** [comment]
Thank you for your reply, is it possible to make a new plugin for that purpose?

**Comment by xyzz** [comment]
It should be possible with enough patches to sceshell

**Comment by alpakeno** [comment]
Unfortunately I don't know much about the patching stuff,
so I hope if possible and also if you have time to make a plugins for that purpose
to handle the captured images path ( and also the one that saving images from the browser )
because the way vita handles the media files is too annoying.
Thanks again.
