### ISSUE TITLE
Not compatible with 3.65.

### ISSUE THREAD

**Issue by Dino1989** [xyzz/pngshot#2]
This was probably to be expected but pngshot is not working with the recently hacked 3.65 firmware. When I try to use it the system freezes and I'm forced to restart.

**Comment by xyzz** [comment]
Unfortunately I do not plan to update to 3.65, so this is up to somebody else to fix...

**Comment by xyzz** [comment]
Fixed by #3 and released as https://github.com/xyzz/pngshot/releases/tag/v1.1

**Comment by StepS-** [comment]
Confirmed to be working.
